; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.41"

; Modules
projects[geostudyabroadprogramsmodule][type] = "module"
projects[geostudyabroadprogramsmodule][download][type] = "git"
projects[geostudyabroadprogramsmodule][download][url] = "https://github.com/nwpointer/facultymodule.git"
projects[geostudyabroadprogramsmodule][download][revision] = "930946e5eda7e5ad43d75b33123d33efb3741d79"

projects[views][version] = "2.11"
projects[cck][version] = "2.8"

