; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.39"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[geostudyabroadprogramsmodule][download][type] = "git"
projects[geostudyabroadprogramsmodule][download][url] = "https://github.com/nwpointer/facultymodule.git"
projects[geostudyabroadprogramsmodule][type] = "module"

